apiVersion: v1
kind: Service
metadata:
  name: node-backend
spec:
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30034 #FOR TESTING PURPOSES ONLY
  type: NodePort    
  # type: ClusterIP
