apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - node-backend
                - mongo
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: react-frontend
        image: chlupnoha/react-frontend:latest
        ports:
        - containerPort: 80
#        env:
#        - name: BACKEND_URL
#          value: "/api"
